# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentmode',
            index=models.Index(fields=['mode_name'], name='idx_payment_mode_name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='payments.paymentmode'),
        ),
        migrations.AddField(
            model_name='paymentreconciliationlog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_logs', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='paymentreconciliationlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_logs', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentreconciliationlog',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='razorpayorder',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='razorpay_orders', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='refund',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_id'], name='idx_webhook_event_id'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['processed_at'], name='idx_webhook_processed'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='idx_payment_invoice'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='idx_payment_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_payment_id'], name='idx_payment_rp_id'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliationlog',
            index=models.Index(fields=['reconciliation_status'], name='idx_recon_status'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliationlog',
            index=models.Index(fields=['created_at'], name='idx_recon_created'),
        ),
        migrations.AddIndex(
            model_name='razorpayorder',
            index=models.Index(fields=['razorpay_order_id'], name='idx_rp_order_id'),
        ),
        migrations.AddIndex(
            model_name='razorpayorder',
            index=models.Index(fields=['invoice'], name='idx_rp_invoice'),
        ),
        migrations.AddIndex(
            model_name='razorpayorder',
            index=models.Index(fields=['order_status'], name='idx_rp_status'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment'], name='idx_refund_payment'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_status'], name='idx_refund_status'),
        ),
    ]
