# Generated by Django 5.2.9 on 2026-01-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_delivery_date', models.DateField()),
                ('scheduled_delivery_time', models.TimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('delivery_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('signature_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_delivery',
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_delivery_days', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'delivery_delivery_zone',
            },
        ),
    ]
