# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['is_active'], name='idx_zone_active'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='delivery.deliveryzone'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order'], name='idx_delivery_order'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_status'], name='idx_delivery_status'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['scheduled_delivery_date'], name='idx_delivery_date'),
        ),
    ]
