# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='generated_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderbill',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='bill', to='orders.order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice', to='billing.orderbill'),
        ),
        migrations.AddIndex(
            model_name='orderbill',
            index=models.Index(fields=['bill_generated_at'], name='idx_bill_generated'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='idx_invoice_number'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='idx_invoice_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='idx_invoice_due'),
        ),
    ]
