# Generated by Django 5.2.9 on 2026-01-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteration_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days', models.PositiveIntegerField(default=3)),
                ('is_included_in_original', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PROPOSED', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trials_alteration',
            },
        ),
        migrations.CreateModel(
            name='RevisedDeliveryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_delivery_date', models.DateField()),
                ('revised_delivery_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trials_revised_delivery_date',
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_location', models.CharField(choices=[('IN_SHOP', 'In Shop'), ('HOME', 'Home Visit')], default='IN_SHOP', max_length=20)),
                ('trial_date', models.DateField()),
                ('trial_time', models.TimeField(blank=True, null=True)),
                ('trial_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('fit_issues', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trials_trial',
            },
        ),
    ]
