# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('trials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alteration',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_alterations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviseddeliverydate',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revised_delivery', to='orders.order'),
        ),
        migrations.AddField(
            model_name='reviseddeliverydate',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='delivery_date_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trial',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_trials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trial',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='orders.order'),
        ),
        migrations.AddField(
            model_name='trial',
            name='scheduled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scheduled_trials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alteration',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alterations', to='trials.trial'),
        ),
        migrations.AddIndex(
            model_name='reviseddeliverydate',
            index=models.Index(fields=['order'], name='idx_revised_order'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['order'], name='idx_trial_order'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['trial_date'], name='idx_trial_date'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['trial_status'], name='idx_trial_status'),
        ),
        migrations.AddIndex(
            model_name='alteration',
            index=models.Index(fields=['trial'], name='idx_alteration_trial'),
        ),
        migrations.AddIndex(
            model_name='alteration',
            index=models.Index(fields=['status'], name='idx_alteration_status'),
        ),
    ]
