# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('assigned_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('pending_orders', models.PositiveIntegerField(default=0)),
                ('average_days_per_order', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reporting_staff_workload',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='InventoryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('quantity_consumed', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('cost_of_consumption', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_reports', to='inventory.fabric')),
            ],
            options={
                'db_table': 'reporting_inventory_consumption',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('completed_orders_count', models.PositiveIntegerField()),
                ('by_garment_type', models.JSONField(blank=True, null=True)),
                ('by_work_type', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reporting_monthly_revenue',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='idx_revenue_year_month')],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PendingOrdersSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('total_pending', models.PositiveIntegerField()),
                ('overdue_orders', models.PositiveIntegerField()),
                ('pending_by_status', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reporting_pending_orders_snapshot',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_date'], name='idx_snapshot_date')],
            },
        ),
    ]
