# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffworkload',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventoryconsumption',
            index=models.Index(fields=['fabric'], name='idx_consumption_fabric'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryconsumption',
            unique_together={('fabric', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='staffworkload',
            index=models.Index(fields=['staff'], name='idx_workload_staff'),
        ),
        migrations.AlterUniqueTogether(
            name='staffworkload',
            unique_together={('staff', 'year', 'month')},
        ),
    ]
