# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_id', models.BigIntegerField(blank=True, null=True)),
                ('cost_per_meter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_in_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_threshold', models.DecimalField(decimal_places=3, default=5.0, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_fabric',
                'indexes': [models.Index(fields=['quantity_in_stock'], name='idx_fabric_quantity'), models.Index(fields=['reorder_threshold'], name='idx_fabric_reorder')],
                'unique_together': {('name', 'color', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_triggered_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('fabric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alert', to='inventory.fabric')),
            ],
            options={
                'db_table': 'inventory_low_stock_alert',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage/Wastage')], max_length=20)),
                ('quantity_meters', models.DecimalField(decimal_places=3, max_digits=10)),
                ('previous_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='inventory.fabric')),
            ],
            options={
                'db_table': 'inventory_stock_transaction',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
