# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lowstockalert',
            index=models.Index(fields=['is_resolved'], name='idx_alert_resolved'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['fabric'], name='idx_stock_tx_fabric'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['order'], name='idx_stock_tx_order'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_date'], name='idx_stock_tx_date'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='idx_stock_tx_type'),
        ),
    ]
