# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('default_advance_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('default_delivery_days', models.PositiveIntegerField(default=7)),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=Decimal('5.0'), max_digits=10)),
                ('urgency_surcharge_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('email_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
                'db_table': 'config_system_configuration',
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=150)),
                ('rule_type', models.CharField(choices=[('GARMENT', 'Garment-based'), ('WORK_TYPE', 'Work Type-based'), ('SEASON', 'Seasonal'), ('BULK', 'Bulk Order')], max_length=20)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('min_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rules', to='catalog.garmenttype')),
            ],
            options={
                'db_table': 'config_pricing_rule',
            },
        ),
    ]
