# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rule_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rules', to='catalog.worktype'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['is_active'], name='idx_rule_active'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['effective_from'], name='idx_rule_effective'),
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['updated_at'], name='idx_config_updated'),
        ),
    ]
