# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_field_name', models.CharField(max_length=100)),
                ('display_label', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('inches', 'Inches'), ('cm', 'Centimeters')], default='inches', max_length=20)),
                ('default_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('description_for_tailor', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'measurements_measurement_template',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'measurements_measurement_value',
            },
        ),
        migrations.CreateModel(
            name='MeasurementSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_sets', to='customers.customerprofile')),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='measurement_sets', to='catalog.garmenttype')),
            ],
            options={
                'db_table': 'measurements_measurement_set',
                'ordering': ['-measurement_date'],
            },
        ),
    ]
