# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('measurements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementset',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurementtemplate',
            name='garment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_templates', to='catalog.garmenttype'),
        ),
        migrations.AddField(
            model_name='measurementvalue',
            name='measurement_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_values', to='measurements.measurementset'),
        ),
        migrations.AddField(
            model_name='measurementvalue',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='values', to='measurements.measurementtemplate'),
        ),
        migrations.AddIndex(
            model_name='measurementset',
            index=models.Index(fields=['customer'], name='idx_meas_set_customer'),
        ),
        migrations.AddIndex(
            model_name='measurementset',
            index=models.Index(fields=['garment_type'], name='idx_meas_set_garment'),
        ),
        migrations.AddIndex(
            model_name='measurementset',
            index=models.Index(fields=['is_default'], name='idx_meas_set_default'),
        ),
        migrations.AddIndex(
            model_name='measurementset',
            index=models.Index(fields=['measurement_date'], name='idx_meas_set_date'),
        ),
        migrations.AddIndex(
            model_name='measurementtemplate',
            index=models.Index(fields=['garment_type'], name='idx_meas_template_garment'),
        ),
        migrations.AlterUniqueTogether(
            name='measurementtemplate',
            unique_together={('garment_type', 'measurement_field_name')},
        ),
        migrations.AddIndex(
            model_name='measurementvalue',
            index=models.Index(fields=['measurement_set'], name='idx_meas_value_set'),
        ),
        migrations.AlterUniqueTogether(
            name='measurementvalue',
            unique_together={('measurement_set', 'template')},
        ),
    ]
