# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fabric_requirement_meters', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('stitching_days_estimate', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_garment_type',
                'indexes': [models.Index(fields=['is_active'], name='idx_garment_is_active'), models.Index(fields=['base_price'], name='idx_garment_base_price')],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('labor_hours_estimate', models.PositiveIntegerField(default=8)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog_work_type',
                'indexes': [models.Index(fields=['name'], name='idx_work_type_name')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('image_filename', models.CharField(max_length=255)),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('is_cover_image', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.garmenttype')),
            ],
            options={
                'db_table': 'catalog_product_image',
                'ordering': ['display_order', '-uploaded_at'],
                'indexes': [models.Index(fields=['garment_type'], name='idx_prod_img_garment'), models.Index(fields=['is_cover_image'], name='idx_prod_img_cover')],
            },
        ),
        migrations.CreateModel(
            name='GarmentWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supported', models.BooleanField(default=True)),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garment_work_types', to='catalog.garmenttype')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garment_work_types', to='catalog.worktype')),
            ],
            options={
                'db_table': 'catalog_garment_work_type',
                'indexes': [models.Index(fields=['garment_type'], name='idx_gwt_garment')],
                'unique_together': {('garment_type', 'work_type')},
            },
        ),
    ]
