# Generated by Django 5.2.9 on 2026-01-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'designs_customization_note',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('design_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('design_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('jpg', 'JPEG'), ('png', 'PNG')], max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'designs_design',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
