# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationnote',
            name='noted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='design_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='design',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='uploaded_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customizationnote',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='designs.design'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['order'], name='idx_design_order'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['is_approved'], name='idx_design_approved'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['file_type'], name='idx_design_file_type'),
        ),
        migrations.AddIndex(
            model_name='customizationnote',
            index=models.Index(fields=['design'], name='idx_custom_note_design'),
        ),
    ]
