# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0003_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermaterialallocation',
            name='allocated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='material_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermaterialallocation',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_allocations', to='inventory.fabric'),
        ),
        migrations.AddField(
            model_name='ordermaterialallocation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='current_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='history_from', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='history_to', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='orderstatustransition',
            name='from_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='orderstatustransition',
            name='to_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='orderworktype',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_work_types', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderworktype',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_work_types', to='catalog.worktype'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['order'], name='idx_assignment_order'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['staff'], name='idx_assignment_staff'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['role_type'], name='idx_assignment_role'),
        ),
        migrations.AddIndex(
            model_name='ordermaterialallocation',
            index=models.Index(fields=['order'], name='idx_allocation_order'),
        ),
        migrations.AlterUniqueTogether(
            name='ordermaterialallocation',
            unique_together={('order', 'fabric')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='idx_order_number'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='idx_order_customer'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['current_status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='idx_order_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['expected_delivery_date'], name='idx_order_delivery'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted'], name='idx_order_deleted'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order'], name='idx_status_history_order'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['changed_at'], name='idx_status_history_date'),
        ),
        migrations.AddIndex(
            model_name='orderstatustransition',
            index=models.Index(fields=['from_status'], name='idx_transition_from'),
        ),
        migrations.AlterUniqueTogether(
            name='orderstatustransition',
            unique_together={('from_status', 'to_status')},
        ),
        migrations.AddIndex(
            model_name='orderworktype',
            index=models.Index(fields=['order'], name='idx_order_work_order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderworktype',
            unique_together={('order', 'work_type')},
        ),
    ]
