# Generated by Django 5.2.9 on 2026-01-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['channel_name'], name='idx_notif_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationtype',
            index=models.Index(fields=['type_name'], name='idx_notif_type_name'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='notifications.notificationtype'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='idx_notif_recipient'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['order'], name='idx_notif_order'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='idx_notif_status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='idx_notif_created'),
        ),
    ]
